### ISSUE TITLE
Missing bibliography.bib

### ISSUE THREAD

**Issue by eturkes** [martinholub/DroNc-seq#1]
Thank you for this awesome project! However, you might want to add the bibliography.bib file, otherwise the Rmd files cannot run. FYI, the ".bib" extension is in your gitignore, not sure why. I only tested dropseq_minimal.Rmd, but adding bibliography.bib with the correct references fixes the problem.

**Comment by martinholub** [comment]
Hi @eturkes , thanks for your nice words. I have added a `bib` file.
